### PR TITLE
Add cobbler repo support

### PR DESCRIPTION
**Pull request by dgivens**
Currently, the client does not support managing cobbler repos. If you attempt to create a profile that contains a repo that does not exist, cobbler will return an error. The end goal of this is to add support to the Terraform cobbler provider plugin.

### CODE REVIEW

**Comment by jtopjian** [comment]
@dgivens I did a quick test of this on a [basic cobbler environment](https://github.com/terraform-providers/terraform-provider-cobbler/blob/master/cobbler/acceptance_env/deploy.sh) and ran into a decoding issue with `yumopts`. You've defined it as a string, but it looks like it should be `map[string]interface{}`. 

It's quite possible your environment didn't have any `yumopts` specified? I have no idea why the single repo in my environment (Ubuntu) had `yumopts` set, but I guess it's good it did :)

Running the following command shows the following output:

```shell
curl -XPOST -d '                    
<methodCall>                        
  <methodName>get_repos</methodName>
  <params>                          
  </params>                         
</methodCall>                       
' http://localhost:25151/           
```

```
...
<member>                         
  <name>yumopts</name>             
  <value>
    <struct>                  
      <member>                         
        <name>--verbose</name>           
        <value><string>~</string></value>
      </member>                        
      <member>                         
        <name>--ignore-release-gpg</name>
        <value><string>~</string></value>
      </member>                        
    </struct>
  </value>                
</member>                        
...
```

Other than that, this looks good to me. Thank you for your work on this. This library was one of my first Go works and reviewing it now, it's a little sloppy, so thank you for finding your way with it :)

**Comment by dgivens** [comment]
This is my first time doing anything with Go, so I wouldn't know good from bad. I'm more of a python guy. 

I've made some changes, and while I don't get an error on build, I get the following error when used in conjunction with the terraform provider:

```
Cobbler Repo: Error Creating: error: "<type 'exceptions.TypeError'>:modify_repo() takes exactly 5 arguments (4 given)" code: 1
```

I'm out of ideas and would love some assistance from someone who has more than not-quite-basic knowledge of Go.

**Comment by jtopjian** [comment]
@dgivens That's no problem at all. I can take a look and see if I can spot the problem. :)

**Comment by dgivens** [comment]
By the way, this is the resource I'm using to test from Terraform:

```
resource "cobbler_repo" "homeawayel_7_x86_64" {
  name = "HomeawayEL-7-x86_64"
  arch = "x86_64"
  breed = "yum"
  mirror_locally = false
  mirror = "http://repo/homeawayel7/"
  yumopts = {"exclude" = "*langpack*"}
}
```

**Comment by jtopjian** [comment]
I see the issue:

Cobbler wants `yumopts` to be a string when sending the request, but is sending a `map[string]interface{}` in the result.

This is going to take me some time to figure out how to best handle it without doing a lot of rewrite to this library. A quick workaround is to simply omit yumopts altogether... unless, of course, you need to use yumopts.

**Comment by dgivens** [comment]
I don't need it for my environments, so I've commented it out for now. Maybe once I know a little more about Go, I can revisit.

**Comment by jtopjian** [comment]
This looks good!

There's an internal change I need to make in order for `Proxy` to work on older cobbler versions (such as what's bundled with Ubuntu 14.04, but that's not a breaker here.

Thank you for your work and for your patience with this PR.

**Pull request merged**
